# Generated by Django 3.0.3 on 2020-04-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchRoutes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight_Routes',
        ),
    ]
